### ISSUE TITLE
responsive fails

### ISSUE THREAD

**Issue by boennemann** [conc-at/conc.at#5]
![screen shot 2015-01-30 at 16 44 46](https://cloud.githubusercontent.com/assets/908178/5978342/7217b5ce-a89f-11e4-930e-4fdbcf9e7db0.png)
![screen shot 2015-01-30 at 16 45 09](https://cloud.githubusercontent.com/assets/908178/5978343/743c5a6c-a89f-11e4-8654-f3a8b5d08d37.png)

**Comment by verpixelt** [comment]
I've opened a pull request for the accommodation rating issue.
